DROP TABLE IF EXISTS `email_templates`;

CREATE TABLE `email_templates`(
	id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`template` VARCHAR(4000) NOT NULL,
	createDateUTC DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP)
);

DROP TABLE IF EXISTS `emails`;

CREATE TABLE `emails`(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	templateId TINYINT UNSIGNED NOT NULL,
    siteId TINYINT UNSIGNED NOT NULL,
    blackBin BIT(1) NOT NULL DEFAULT b'0',
    greenBin BIT(1) NOT NULL DEFAULT b'0',
    `reference` VARCHAR(100) NULL,
	sentDateUTC DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP)
);
CREATE INDEX ix_emails_siteId_blackBin_greenBin ON emails (siteId, blackBin, greenBin);
CREATE INDEX ix_emails_siteId_sentDateUTC ON emails (siteId, sentDateUTC);

DROP TABLE IF EXISTS `news`;

CREATE TABLE `news`(
	id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`message` VARCHAR(500) NOT NULL,
	displayFromUTC DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP),
    displayUntilUTC DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP),
	createDateUTC DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP)
);
CREATE INDEX ix_news_displayFromUTC_displayUntilUTC ON news (displayFromUTC, displayUntilUTC);

DROP TABLE IF EXISTS `sites`;

CREATE TABLE `sites`(
	id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(100) NOT NULL,
	`address` VARCHAR(500) NOT NULL,
    `additionalInfo` VARCHAR(500) NOT NULL,
	createDateUTC DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP)
);